name: Merge

on:
  issue_comment:
    types: [created]

jobs:
  fast-forward:
    # Only run if the comment contains the /merge command.
    if: ${{ contains(github.event.comment.body, '/merge')
      && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BUILD_APP_ID }}
          private-key: ${{ secrets.BUILD_PRIVATE_KEY }}
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          github_token: ${{ steps.app-token.outputs.token }}
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: 'on-error'
